### ISSUE TITLE
Sharing of pretrained checkpoints

### ISSUE THREAD

**Issue by shuqike** [inspire-group/DP-RandP#2]
Could you share the pretrained checkpoints from Phase I? We are trying to reproduce Figure 6 in your paper. Thank you!

**Comment by txy15** [comment]
Thank you for your interest of our work! Here is the link for checkpoint after Phase I. [checkpoint](https://www.dropbox.com/scl/fi/2epqw07ycpba99py8z67u/encoder.pth?rlkey=w7oq6y4ob8l6aiukjdkg4cjcf&dl=0)

**Comment by shuqike** [comment]
Thanks!
